### ISSUE TITLE
Vim Toggle Key Custom

### ISSUE THREAD

**Issue by daniel081009** [tonisives/vim#1]
title is content

**Comment by tonisives** [comment]
What do you mean exactly? Like add more toggle key variants on top of current ones? What keys do you suggest?

**Comment by odanwhi** [comment]
Yes I want the combination command + shift + [  Or command + [
Thank!

**Comment by odanwhi** [comment]
Is it possible to automatically disable when I select a specific program? For example vscode, obsidian

**Comment by tonisives** [comment]
> 

Currently only keys available in the UI are supported and I don't plan to add new ones.

You can change it manually in `~/.config/karabiner/karabiner.json`

You need to change lines
https://github.com/tonisives/vim/blob/main/karabiner.json#L39
and
https://github.com/tonisives/vim/blob/main/karabiner.json#L88
and
https://github.com/tonisives/vim/blob/main/karabiner.json#L116

to

```
"from": {
    "key_code": "open_bracket",
    "modifiers": {
        "mandatory": [
            "command"
        ]
    }
},
```
or similar.
check karabiner keycodes [here](https://github.com/pqrs-org/Karabiner-Elements/issues/925)

**Comment by tonisives** [comment]
> Is it possible to automatically disable when I select a specific program? For example vscode, obsidian

I have implemented this and plan to make a release in a week or 2

**Comment by odanwhi** [comment]
Thank!
