### ISSUE TITLE
Does it work on MDM enrolled macbook? 

### ISSUE THREAD

**Issue by heefan** [tonisives/vim#10]
Hi there, 
My macbook is MDM enrolled which is managed by company. I used to work with Karabiner without any issue before upgrading to macos 15.0.1. 

I'd like to try your app, however, the website mentions it is free for 7 days. But I downloaded and installed the v2.3 dmg app, it request to input license. 

Does it still have 7 days free trial?  Thanks.

**Comment by tonisives** [comment]
Hi, if Karabiner worked for you before, then this app should work as well.

The big dependency is Karabiner really. But then we also have the another signed app that shows the vim indicator and settings. The ti-vim .dmg installer will install both of these apps. You could also install Karabiner yourself, and then download the standalone ti-vim version(.zip, not .dmg).

You can try and I can fully refund if it doesn't work/you are not happy in 7 days.

**Comment by heefan** [comment]
Gotcha and thanks for your confirmation.

**Comment by heefan** [comment]
Gotcha and thanks for your confirmation.
