### ISSUE TITLE
unable to get past setup 

### ISSUE THREAD

**Issue by jonch070** [tonisives/vim#3]
unable to get past karabiner daemon phase of setup

**Comment by tonisives** [comment]
Hi,

this happened for me also when I had Karabiner previously installed, and tried to install ti-vim.


What fixed it for me was to 
* quit the ti-vim app.
* remove these 2 items from the Input monitoring (press `-` to completely remove them from the list)
* start the tutorial again


If not working, then for the next step could also try `Try reinstalling the app` from the [docs](https://vim.tonisives.com/docs/) (if possible)

**Comment by jonch070** [comment]
thank you!
