### ISSUE TITLE
editing karabiner.json

### ISSUE THREAD

**Issue by burgessa23** [tonisives/vim#8]
Hi,

I manually modified my karabiner.json, and it seems to have upset ti-vim. Once I saved my changes, the settings app would no longer open. I ran `defaults delete com.tonisives.ti-vim` and it's working again now, but it reset karabiner.json to only contain the config added by ti-vim.

Is this expected? If so, how would I go about customizing the config, or using my existing karabiner settings?

**Comment by tonisives** [comment]
Hi, I also have custom karabiner rules. They should work if you add your them before the `(ti-vim)` ones. That is how I have it.

eg:
```json
      "rules": [
          {
              "description": "my custom modification",
              "manipulators": [
                  {
                      "conditions": [],


"[...]"

          {
              "description": "(ti-vim) {vim_key} -> on, {vim_key}, esc, control+[ or any pointing_button -> off",
              "manipulators": [
                  {
                      "conditions": [
                          {
 
```


It should also work if you add your custom modifications before installing/resetting ti-vim. Then, ti-vim should add it's `(ti-vim)` modifications after the custom ones automatically

**Comment by burgessa23** [comment]
Thanks, that makes sense. I assume it's ok to change the mappings added by ti-vim to fit how I have vim setup?

Also, can I run karabiner elements alongside ti-vim? Or will it conflict?

**Comment by tonisives** [comment]
>  can I run karabiner elements alongside ti-vim?

Karabiner elements needs to run along side ti-vim. If you have a custom Karabiner installation, then you can install ti-vim as a standalone app (as written in [downloads](https://vim.tonisives.com/download.html))

>  change the mappings added by ti-vim to fit how I have vim setup

You can change ti-vim modifications. Just make sure to check and retain the messages to ti-vim app:

```json
    "shell_command": "osascript -e 'tell application \"ti-vim\" to indicator 0'"
```

Please note, that ti-vim app will reset the `(ti-vim)` mappings to default ones after
- changing the `Vim mode key`
- adding `Rules`
- reinstalling the app
