### ISSUE TITLE
Mode Indicator not showing while apps are fullscreen

### ISSUE THREAD

**Issue by TheDataSeneschal** [tonisives/vim#9]
I know this is probably a MacOS thing, but since I use all my apps in fullscreen mode, I just wanted to see if this was possible?

**Comment by tonisives** [comment]
Hi, this is currently not possible. The indicator is an NSWindow object, and therefore cannot be overlaid in full screen mode which shows 1 window only

**Comment by TheDataSeneschal** [comment]
Ok, thanks for the clarification and quick response. Please keep up the
good work.

**Comment by TheDataSeneschal** [comment]
Ok, that's fine. Thanks for the quick reply and please keep up the good work!
